# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_auto_20170303_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooksFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', django_fsm.FSMField(default='ADD', max_length=50, protected=True)),
            ],
        ),
    ]
