# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_booksflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksflow',
            name='book_id',
            field=models.IntegerField(default=b'1'),
        ),
    ]
